export const sitemapServices: string[] = [
  "ISEE form",
  "ISEE Form for Minors",
  "Tax Consulting",
  "Six-monthly management of housekeepers, carers and babysitters",
  "Universal Single Allowance",
  "University ISEE Form",
  "Signing a Rental Agreement",
  "Payroll Processing for Housekeepers, Caregivers, and Babysitters",
  "Pending Charges",
  "CU Single Certification (Ex. CUD INPS)",
  "Land registry search",
  "Drafting Contracts for Housekeepers, Caregivers, and Babysitters",
  "Criminal record",
  "Old Age Pension",
];
